// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsr9_cw6iayFHfVJQYkMeuJDYwnJK4Ujk',
    appId: '1:9174455462:web:3beb11dd1aa8ae3af2d067',
    messagingSenderId: '9174455462',
    projectId: 'klproind-user-app',
    authDomain: 'klproind-user-app.firebaseapp.com',
    storageBucket: 'klproind-user-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsaBhDaG0zn3Il4ELArmm8WI-_v4geNOw',
    appId: '1:9174455462:android:92e29fe168b9f7a2f2d067',
    messagingSenderId: '9174455462',
    projectId: 'klproind-user-app',
    storageBucket: 'klproind-user-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLpxCqD7G_a4uYcSsNGMtIoTInEQexl4',
    appId: '1:9174455462:ios:4a5d1410c35b284cf2d067',
    messagingSenderId: '9174455462',
    projectId: 'klproind-user-app',
    storageBucket: 'klproind-user-app.firebasestorage.app',
    iosClientId: '9174455462-qs0ji6a67udnvas878kps0si17739v9b.apps.googleusercontent.com',
    iosBundleId: 'com.softfix.ondemandservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsr9_cw6iayFHfVJQYkMeuJDYwnJK4Ujk',
    appId: '1:9174455462:web:3beb11dd1aa8ae3af2d067',
    messagingSenderId: '9174455462',
    projectId: 'klproind-user-app',
    authDomain: 'klproind-user-app.firebaseapp.com',
    storageBucket: 'klproind-user-app.firebasestorage.app',
  );
}